```{r table_priorite, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(tibble)

priorite <- tribble(
  ~Bloc, ~Condition, ~Contenu, ~Reference,
  "(I) Celui qui / son ayant cause", "Preuve ?", "", "A87(1) CBE",
  "", "Prio. valable à l’OEB",
  "présomption réfragable du droit de priorité", "G1/22, G2/22",
  "", "Prio. valable à l’INPI",
  "une « copie de la demande antérieure »<br>
   une « autorisation de revendiquer la priorité donnée par écrit
   par le propriétaire de la demande antérieure »",
  "Cass arrêt n° 537 FS-B",

  "(II) Rég. déposé dans ou pour", "État partie à l’OMC ?", "", "A87(1) CBE",
  "", "Prio. pas valable à l’OEB", "avant 13/12/2007", "G2/02, G3/02",
  "", "Prio. valable à l’OEB", "après 13/12/2007 (inclus)", "CBE 2000",
  "", "État accédant à CUP ou OMC ?", "", "",
  "", "Prio. valable à l’OEB",
  "accord en vigueur à la date de la priorité, ET<br>
   législation applicable à la date de dépôt", "",

  "(III) La même inv.", "Fondement ?", "", "A87(1) CBE",
  "", "Prio. valable",
  "(i) allouer des dates de priorité à l’intérieur d’une revendication
   de la demande sous priorité<br>
   « suffisamment décrit » dans la demande antérieure<br>
   (ii) DDSA de l’ensemble des pièces de la demande antérieure",
  "G1/15, G2/98",
  "", "Prio. pas valable",
  "combiner des documents sans lien entre eux à la manière d’une mosaïque<br>
   un état de la technique cité dans la description de la demande antérieure<br>
   un disclaimer décrit dans la description de la demande antérieure",
  "Directives F-VI, 1.5 ; F-VI, 2.2",

  "(IV) Délai de 12 mois", "Calcul ?", "", "A87(1) CBE",
  "", "",
  "(i) appliquer la règle 131(4) pour le calcul du délai", "R131(4)",
  "", "",
  "(ii) appliquer la règle 134(1) à (4) pour les prorogations de délai",
  "R134(1)–(4)",
  "", "",
  "(iii) appliquer la règle 133 pour la fiction de respect du délai
   pour les pièces reçues tardivement ; la règle 134(5) pour la fiction
   de respect pour les envois postaux",
  "R133, R134(5)",

  "(V) première dem.", "Cf. 2.", "", ""
)

priorite %>% 
  kable(
    format = "html",           # mettre "latex" si tu rends en PDF
    escape = FALSE,
    col.names = c("Bloc", "Condition", "Contenu", "Référence"),
    caption = "1. Vérifier une priorité"
  ) %>% 
  kable_styling(
    full_width = FALSE,
    bootstrap_options = c("striped", "condensed", "hover")
  ) %>% 
  collapse_rows(columns = 1, valign = "top")

